# Generated by Django 4.2.2 on 2023-06-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisheries_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marina',
            table='Marina',
        ),
    ]
