# Generated by Django 4.2.2 on 2023-06-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisheries_management', '0002_alter_marina_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marina',
            table='marina',
        ),
    ]
