# Generated by Django 4.2.2 on 2023-06-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisheries_management', '0004_vehicle_worksheet_fishermen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='MId',
            new_name='Mid',
        ),
    ]
