# Generated by Django 4.2.2 on 2023-06-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisheries_management', '0005_rename_mid_vehicle_mid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='Mid',
            new_name='MId',
        ),
    ]
